name: notify-build

on:
  push:
    branches: [ "*" ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ master ]
  workflow_dispatch:

jobs:        
  Android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-android-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode and save keystore
        env:
         ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
        run: |
         echo "$ANDROID_KEYSTORE_B64" | base64 --decode > ${{ github.workspace }}/android/app/ks.jks

      - name: Check isPr
        id: get_is_pr
        run: |
          is_pr=${{ github.event_name == 'pull_request' }}
          echo "::set-output name=is_pr::$is_pr"

      - name: Setup libs
        run: |
            wget -P android/app/libs \
            https://github.com/uzu09811/winlator-lib/releases/download/debug/win-debug.aar
      
      - name: Build with Gradle
        run: |
          cd android/ 
          chmod +x gradlew
          ./gradlew assembleRelease
          cd ../..
        env:
          ANDROID_KEYSTORE_FILE: ks.jks
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          GITHUB_TOKEN: ${{ secrets.BUILD }}
          IS_PR: ${{ steps.get_is_pr.outputs.is_pr }}
        

      - name: Upload Android Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notify-android
          path: ./android/app/build/outputs/apk/release/app-release.apk
  
